## Imports

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV, learning_curve
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.dummy import DummyRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error



## Load Data 

In [2]:
IGDB = pd.read_csv('./data/IGDB_pre_processing.csv')

In [3]:
IGDB.head().T

0  \
Unnamed: 0                                                           0   
id                                                                7995   
age_ratings                                                    [66005]   
category                                                             0   
collection                                                      3138.0   
cover                                                         199764.0   
created_at                                                  1414716913   
external_games                       [52206, 132934, 1746061, 1921468]   
first_release_date                                          2007-03-11   
follows                                                            NaN   
game_modes                                                         [1]   
genres                                                             [8]   
involved_companies                            [229976, 229977, 229978]   
keywords                                                   [690, 2387]   
name                          El Tigre: The Adventures of Manny Rivera   
platforms                                                       [5, 8]   
player_perspectives                                                [2]   
release_dates                                         [511745, 511746]   
screenshots                                                    [27813]   
similar_games        [20342, 24426, 28070, 29032, 55190, 57187, 631...   
slug                           el-tigre-the-adventures-of-manny-rivera   
summary              Havoc has been unleashed on Miracle City! Scor...   
tags                              [1, 268435464, 536871602, 536873299]   
themes                                                             [1]   
updated_at                                                  1693874906   
url                  https://www.igdb.com/games/el-tigre-the-advent...   
websites                                              [254124, 395703]   
checksum                          a17db3a2-98e7-fff0-1310-2dd6cd7f21d7   
total_rating                                                      65.0   
total_rating_count                                                 1.0   
rating_count                                                       NaN   
console                                                            1.0   
operating_system                                                   0.0   
year                                                              2007   

                                                                     1  \
Unnamed: 0                                                           1   
id                                                                4221   
age_ratings                                                    [58455]   
category                                                             0   
collection                                                       687.0   
cover                                                         161022.0   
created_at                                                  1390750383   
external_games                                [51645, 143610, 1709454]   
first_release_date                                          2002-06-03   
follows                                                            NaN   
game_modes                                                      [1, 4]   
genres                                                     [4, 14, 25]   
involved_companies                               [10934, 10935, 10936]   
keywords             [61, 129, 632, 977, 982, 1440, 4228, 4903, 649...   
name                                                    UFC: Throwdown   
platforms                                                      [8, 21]   
player_perspectives                                                [2]   
release_dates                                             [9923, 9924]   
screenshots                                                        NaN  

In [4]:
IGDB.drop('Unnamed: 0', axis=1, inplace=True)

In [5]:
IGDB.dtypes

id                       int64
age_ratings             object
category                 int64
collection             float64
cover                  float64
created_at               int64
external_games          object
first_release_date      object
follows                float64
game_modes              object
genres                  object
involved_companies      object
keywords                object
name                    object
platforms               object
player_perspectives     object
release_dates           object
screenshots             object
similar_games           object
slug                    object
summary                 object
tags                    object
themes                  object
updated_at               int64
url                     object
websites                object
checksum                object
total_rating           float64
total_rating_count     float64
rating_count           float64
console                float64
operating_system       float64
year    

In [6]:
IGDB.shape

(4265, 33)

In [7]:
len(IGDB) * .7, len(IGDB) * .3

(2985.5, 1279.5)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(IGDB.drop(columns='total_rating'), 
                                                    IGDB.total_rating, test_size=0.3, 
                                                    random_state=47)

In [9]:
X_train.shape, X_test.shape

((2985, 32), (1280, 32))

In [10]:
y_train.shape, y_test.shape

((2985,), (1280,))

In [11]:
#drop non-numeric columns from `X_train` and `X_test`.
names_list = IGDB.select_dtypes(include=['object'])

In [12]:
names_list_columns = names_list.columns

In [13]:
names_train = X_train[names_list_columns]
names_test = X_test[names_list_columns]
X_train.drop(columns=names_list_columns, inplace=True)
X_test.drop(columns=names_list_columns, inplace=True)
X_train.shape, X_test.shape

((2985, 12), (1280, 12))

In [14]:
X_train.dtypes

id                      int64
category                int64
collection            float64
cover                 float64
created_at              int64
follows               float64
updated_at              int64
total_rating_count    float64
rating_count          float64
console               float64
operating_system      float64
year                    int64
dtype: object

In [15]:
X_test.dtypes

id                      int64
category                int64
collection            float64
cover                 float64
created_at              int64
follows               float64
updated_at              int64
total_rating_count    float64
rating_count          float64
console               float64
operating_system      float64
year                    int64
dtype: object

In [16]:
dumb_reg = DummyRegressor(strategy='mean')
dumb_reg.fit(X_train, y_train)
dumb_reg.constant_

array([[69.06432161]])

In [17]:
train_mean = y_train.mean()
train_mean

69.0643216080402

In [18]:
y_tr_pred_ = train_mean * np.ones(len(y_train))
y_tr_pred_[:5]

array([69.06432161, 69.06432161, 69.06432161, 69.06432161, 69.06432161])

In [19]:
y_tr_pred = dumb_reg.predict(X_train)
y_tr_pred[:5]

array([69.06432161, 69.06432161, 69.06432161, 69.06432161, 69.06432161])

In [20]:
y_te_pred = train_mean * np.ones(len(y_test))

In [21]:
r2_score(y_train, y_tr_pred), r2_score(y_test, y_te_pred)

(0.0, -0.00024439880428972494)

In [22]:
mean_absolute_error(y_train, y_tr_pred), mean_absolute_error(y_test, y_te_pred)

(10.976166595119652, 10.723575690954773)

In [23]:
mean_squared_error(y_train, y_tr_pred), mean_squared_error(y_test, y_te_pred)

(205.6240034342567, 195.37713035971314)